{% set name = "abacusutils" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/abacusutils-{{ version }}.tar.gz
  sha256: 57e3e511e4736256c5d0ff535ef0abbf4d05859fe1f69df6d98ffe66f478b933

build:
  entry_points:
    - pipe_asdf = abacusnbody.data.pipe_asdf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - numpy >=1.16
    - python-blosc >=1.9.2
    - astropy >=4.0.0
    - scipy >=1.5.0
    - numba >=0.50
    - asdf >=2.8
    - h5py
    - pyyaml
    - corrfunc >=2

test:
  imports:
    - abacusnbody.data
    - abacusnbody.hod
  commands:
    - pip check
    - pipe_asdf --help
  requires:
    - pip

about:
  home: https://github.com/abacusorg/abacusutils
  summary: Python and C/C++ code to read halo catalogs and other Abacus N-body data products
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
