{% set name = "abacusutils" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/abacusutils-{{ version }}.tar.gz
  sha256: e49562cac5e1ea2220b57eb173d3d5015169bddfe5f7939996d8848917ae1d4f

build:
  entry_points:
    - pipe_asdf = abacusnbody.data.pipe_asdf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.7
    - setuptools >=61
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - numpy >=1.16
    - python-blosc >=1.9.2
    - astropy-base >=4.0.0
    - scipy >=1.5.0
    - numba >=0.56
    - asdf >=2.8
    - h5py
    - pyyaml
    - asdf-astropy >=0.3
    - msgpack-python >=1
    - parallel-numpy-rng >=0.1.2

test:
  imports:
    - abacusnbody.data
    - abacusnbody.hod
  commands:
    - pip check
    - pipe_asdf --help
  requires:
    - pip

about:
  home: https://github.com/abacusorg/abacusutils
  summary: Python and C/C++ code to read halo catalogs and other Abacus N-body data products
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
